Third branch
dubtouch/Projects pull request #4
Opened 2021-08-20 18:23 UTC by dubtouch

2021-08-20 18:52 UTC, V-Negura requested changes

2021-08-20 18:52 UTC, V-Negura commented on MineSweeper/src/minesweeper/MineSweeper.java
> +                        if (!field[a][b].isMine() && field[a][b].getSymbol() == '.' || !field[a][b].isMine() && field[a][b].getSymbol() == '*') {
`field[a][b].getSymbol == '.'` should be a cell method as well as `field[a][b].getSymbol() == '*'`

2021-08-20 18:52 UTC, V-Negura commented on MineSweeper/src/minesweeper/MineSweeper.java
> +    public void setField(int mines) {
Shouldn't this be private ?

2021-08-20 18:52 UTC, V-Negura commented on MineSweeper/src/minesweeper/MineSweeper.java
> +    public void printField() {
Shouldn't this be private ?

2021-08-20 18:52 UTC, V-Negura commented on MineSweeper/src/minesweeper/MineSweeper.java
> +    public void printFieldWithMines() {
Shouldn't this be private ?

2021-08-20 18:52 UTC, V-Negura commented on MineSweeper/src/minesweeper/MineSweeper.java
> +    public void checkCell(int i, int j) {
Shouldn't this be private ?

2021-08-20 18:52 UTC, V-Negura commented on MineSweeper/src/minesweeper/MineSweeper.java
> +            int h = rand.nextInt(9);
Be more specify

2021-08-20 18:52 UTC, V-Negura commented on MineSweeper/src/minesweeper/MineSweeper.java
> +            int w = rand.nextInt(9);
Be more specify

2021-08-21 10:27 UTC, dubtouch commented on MineSweeper/src/minesweeper/MineSweeper.java
> +                        if (!field[a][b].isMine() && field[a][b].getSymbol() == '.' || !field[a][b].isMine() && field[a][b].getSymbol() == '*') {
resolved

2021-08-21 10:27 UTC, dubtouch commented on MineSweeper/src/minesweeper/MineSweeper.java
> +    public void setField(int mines) {
resolved

2021-08-21 10:27 UTC, dubtouch commented on MineSweeper/src/minesweeper/MineSweeper.java
> +    public void printField() {
resolved

2021-08-21 10:27 UTC, dubtouch commented on MineSweeper/src/minesweeper/MineSweeper.java
> +    public void printFieldWithMines() {
resolved

2021-08-21 10:27 UTC, dubtouch commented on MineSweeper/src/minesweeper/MineSweeper.java
> +    public void checkCell(int i, int j) {
resolved

2021-08-21 10:28 UTC, dubtouch commented on MineSweeper/src/minesweeper/MineSweeper.java
> +            int h = rand.nextInt(9);
resolved

2021-08-21 10:28 UTC, dubtouch commented on MineSweeper/src/minesweeper/MineSweeper.java
> +            int w = rand.nextInt(9);
resolved

2021-08-21 16:18 UTC, V-Negura approved these changes

2021-08-21 16:26 UTC, negura approved these changes

2021-08-21 16:27 UTC, merged